### ISSUE TITLE
Fort Solis Appid 1931730 (Wrong executable filename)

### ISSUE THREAD

**Issue by Stonga2** [Sak32009/Achievement-Watcher#1]
The executable filename for this game is wrong, even on SteamDB.

It's not "Sycamore.exe" as stated on SteamDB. It's "fortsolis.exe".

**Comment by Sak32009** [comment]
Fixed! https://github.com/Sak32009/Achievement-Watcher/commit/f67c53293a75f2cd2358604de829803a1460a20c
